baseURL = 'https://vlek.github.io'
languageCode = 'en-us'
title = "Vlek's Personal Blog"
theme = "etch"

[params]
description = "A random collection of stuff I didn't want to forget"
copyright = "Copyright Â© 2022 Vlek"

[permalinks]
posts = "/:title/"

[markup]
[markup.highlight]
style = 'dracula'
[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 1
[markup.goldmark.renderer]
unsafe = true
footnote = true
